service: jimbere-fund-blog-service

provider:
  name: aws
  runtime: nodejs4.3

functions:
  create:
    handler: src/index.create
    events:
      - http: POST blog
  delete:
    handler: src/index.delete
    events:
      - http: DELETE blog/{id}
        request:
          parameters:
            paths:
              id: true
  publish:
    handler: src/index.publish
    events:
      - http: PUT blog/{id}/publish
        request:
          parameters:
            paths:
              id: true
  read:
    handler: src/index.read
    events:
      - http: GET blog/{id}
  update:
    handler: src/index.update
    events:
      - http: PUT blog/{id}
        request:
          parameters:
            paths:
              id: true
